/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./layouts/**/*.html",
    "./content/**/*.md",
  ],
  theme: {
    extend: {
      colors: {
        "surface": "#faf9f6",
        "on-primary-container": "#8293b6",
        "on-surface": "#1a1c1a",
        "on-tertiary-fixed": "#0d1c2e",
        "inverse-on-surface": "#f1f1ee",
        "primary-container": "#1a2b49",
        "background": "#faf9f6",
        "secondary": "#815607",
        "secondary-container": "#ffc571",
        "outline": "#75777e",
        "outline-variant": "#c5c6ce",
        "error": "#ba1a1a",
        "primary-fixed-dim": "#b6c7ec",
        "on-primary-fixed-variant": "#364766",
        "on-secondary-fixed-variant": "#624000",
        "on-primary": "#ffffff",
        "surface-container-high": "#e9e8e5",
        "primary-fixed": "#d7e2ff",
        "on-secondary-fixed": "#291800",
        "on-tertiary-container": "#8593aa",
        "error-container": "#ffdad6",
        "tertiary-fixed": "#d5e3fc",
        "surface-container-low": "#f4f3f1",
        "surface-container-lowest": "#ffffff",
        "surface-container": "#efeeeb",
        "secondary-fixed-dim": "#f6bc69",
        "surface-tint": "#4e5e7f",
        "tertiary-container": "#1e2c3e",
        "on-error-container": "#93000a",
        "tertiary": "#081729",
        "inverse-surface": "#2f312f",
        "on-surface-variant": "#44474e",
        "tertiary-fixed-dim": "#b9c7df",
        "surface-dim": "#dbdad7",
        "on-secondary": "#ffffff",
        "on-background": "#1a1c1a",
        "on-tertiary-fixed-variant": "#3a485b",
        "secondary-fixed": "#ffddb2",
        "surface-variant": "#e3e2e0",
        "on-primary-fixed": "#081b38",
        "surface-bright": "#faf9f6",
        "on-secondary-container": "#794f00",
        "on-error": "#ffffff",
        "surface-container-highest": "#e3e2e0",
        "inverse-primary": "#b6c7ec",
        "primary": "#031633",
        "on-tertiary": "#ffffff"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "margin": "1.25rem",
        "space-sm": "0.5rem",
        "space-xl": "2.5rem",
        "space-xs": "0.25rem",
        "space-md": "1rem",
        "gutter": "1.5rem",
        "space-lg": "1.5rem",
        "margin-tablet": "2.5rem",
        "margin-desktop": "4rem",
        "gutter-desktop": "2.5rem"
      },
      fontFamily: {
        "body-md": ["\"Source Sans 3\"", "sans-serif"],
        "label-uppercase": ["\"Source Sans 3\"", "sans-serif"],
        "quote-scholarly": ["\"EB Garamond\"", "serif"],
        "headline-md": ["\"EB Garamond\"", "serif"],
        "body-lg": ["\"Source Sans 3\"", "sans-serif"],
        "headline-sm": ["\"EB Garamond\"", "serif"],
        "display-hero": ["\"EB Garamond\"", "serif"],
        "display-hero-mobile": ["\"EB Garamond\"", "serif"],
        "headline-lg-mobile": ["\"EB Garamond\"", "serif"],
        "headline-lg": ["\"EB Garamond\"", "serif"],
        "body-sm": ["\"Source Sans 3\"", "sans-serif"],
        "label-md": ["\"Source Sans 3\"", "sans-serif"]
      },
      fontSize: {
        "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "label-uppercase": ["12px", { "lineHeight": "16px", "letterSpacing": "0.08em", "fontWeight": "600" }],
        "quote-scholarly": ["22px", { "lineHeight": "32px", "fontWeight": "400" }],
        "headline-md": ["26px", { "lineHeight": "34px", "fontWeight": "600" }],
        "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }],
        "headline-sm": ["20px", { "lineHeight": "28px", "fontWeight": "600" }],
        "display-hero": ["48px", { "lineHeight": "56px", "letterSpacing": "-0.015em", "fontWeight": "400" }],
        "display-hero-mobile": ["34px", { "lineHeight": "42px", "letterSpacing": "-0.01em", "fontWeight": "400" }],
        "headline-lg-mobile": ["28px", { "lineHeight": "36px", "letterSpacing": "0em", "fontWeight": "500" }],
        "headline-lg": ["36px", { "lineHeight": "44px", "letterSpacing": "-0.01em", "fontWeight": "500" }],
        "body-sm": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
        "label-md": ["14px", { "lineHeight": "20px", "fontWeight": "600" }]
      }
    }
  },
  plugins: [
    require('@tailwindcss/typography'),
  ],
}
